FROM node:16
WORKDIR /app
RUN curl -fsSL https://download.docker.com/linux/static/stable/x86_64/docker-20.10.9.tgz | tar -xzvf - docker/docker -C . --strip-components 1 && mv docker /usr/bin/docker
EXPOSE 3333
COPY scripts/init*.sh /usr/local/bin
RUN chmod +x /usr/local/bin/init*.sh
ENTRYPOINT []